/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenrouterOauthCallbackRouteImport } from './routes/openrouter-oauth-callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryStoryIdRouteImport } from './routes/story.$storyId'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const OpenrouterOauthCallbackRoute = OpenrouterOauthCallbackRouteImport.update({
  id: '/openrouter-oauth-callback',
  path: '/openrouter-oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdRoute = StoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/openrouter-oauth-callback': typeof OpenrouterOauthCallbackRoute
  '/api/$': typeof ApiSplatRoute
  '/story/$storyId': typeof StoryStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/openrouter-oauth-callback': typeof OpenrouterOauthCallbackRoute
  '/api/$': typeof ApiSplatRoute
  '/story/$storyId': typeof StoryStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/openrouter-oauth-callback': typeof OpenrouterOauthCallbackRoute
  '/api/$': typeof ApiSplatRoute
  '/story/$storyId': typeof StoryStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/openrouter-oauth-callback' | '/api/$' | '/story/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/openrouter-oauth-callback' | '/api/$' | '/story/$storyId'
  id:
    | '__root__'
    | '/'
    | '/openrouter-oauth-callback'
    | '/api/$'
    | '/story/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenrouterOauthCallbackRoute: typeof OpenrouterOauthCallbackRoute
  ApiSplatRoute: typeof ApiSplatRoute
  StoryStoryIdRoute: typeof StoryStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openrouter-oauth-callback': {
      id: '/openrouter-oauth-callback'
      path: '/openrouter-oauth-callback'
      fullPath: '/openrouter-oauth-callback'
      preLoaderRoute: typeof OpenrouterOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenrouterOauthCallbackRoute: OpenrouterOauthCallbackRoute,
  ApiSplatRoute: ApiSplatRoute,
  StoryStoryIdRoute: StoryStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
